services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image:  jk112358/diabetes_predictor_py:23f07ff
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
