name: "diabetes_predictor"

channels:
  - conda-forge
  - defaults
  
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-learn=1.3.2
  - altair=5.5.0
  - jupyterlab=4.2.6
  - vegafusion=2.0.1
  - vl-convert-python=1.7.0
  - matplotlib=3.9.2
  - pandera=0.21.0
  - conda-lock=2.5.7
  - mamba=1.5.11
  - pip
#  - pip:
#    - altair_ally==0.1.1
#    - deepchecks==0.18.1
