name: "diabetes"

channels:
  - conda-forge
  - defaults
  
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - altair
  - jupyterlab
  - vegafusion==1.6.9
  - vl-convert-python>=1.6.0

  - pip:
    - altair_ally>=0.1.1 
  